language: python
sudo: false
matrix:
  include:
  - python: '3.8'
    env: TOXENV=py38
  - python: 'pypy3'
    env: TOXENV=pypy3
install:
- pip install -U setuptools pip wheel "tox>=3.4.0" python-coveralls
script:
- env | sort
- python setup.py bdist_wheel
- tox
after_success:
- coverage combine
- coverage report
- coveralls
deploy:
  provider: pypi
  twine_version: 1.13.0
  user: mete0r
  password:
    secure: EeecjW4fW5Nq+Mo/IINrqDiTvCpRBKBkznjwIA7XUQ59ox1vE0kEdun05JOgwIdt9w9lWt8Thum/BmIfG2J/35SIj7Xrv7ans0UvbtOodaED5jb5v7peV6ug0EOV7wukFWVVvLXuIjMNXQV5NgKxqy2wy24NGLGB3F+dGHDUCr8=
  on:
    tags: true
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
